## Deliverable 2. Create a Customer Travel Destinations Map.

In [12]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import requests as req
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv('../Weather_Database/WeatherPy_Database.csv')
city_data_df.head()

,City ID,City,Country,Lat,Lon,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Viedma,AR,-40.8135,-62.9967,53.10,62,87,9.95,light rain
1,1,Mar Del Plata,AR,-38.0023,-57.5575,55.13,52,0,1.01,clear sky
2,2,Marzuq,YE,14.4000,46.4667,75.67,64,92,8.14,overcast clouds
3,3,Punta Arenas,CL,-53.1500,-70.9167,37.51,75,75,8.05,broken clouds
4,4,Komsomolskiy,UZ,40.4272,71.7189,75.92,38,59,6.91,broken clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input('What is the minimum temperature you would like for your trip?'))
max_temp = float(input('What is the maximun temperature you would like for your trip?'))

What is the minimum temperature you would like for your trip?10
What is the maximun temperature you would like for your trip?60

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df['Max Temp'] >= min_temp) & (city_data_df['Max Temp'] <= max_temp)]

preferred_cities_df.sort_values(['Max Temp'], ascending = False)

,City ID,City,Country,Lat,Lon,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
499,499,Lensk,RU,60.7253,114.9278,59.70,52,7,3.67,clear sky
274,274,Richards Bay,ZA,-28.7830,32.0377,59.67,87,0,5.91,clear sky
627,627,Ilo,PE,-17.6394,-71.3375,59.50,81,87,0.65,overcast clouds
248,248,Gujan-Mestras,FR,44.6333,-1.0667,59.47,88,0,2.30,clear sky
71,71,Melioratorov,RU,57.2107,65.6077,59.38,100,75,8.95,broken clouds
...,...,...,...,...,...,...,...,...,...,...
539,539,Rio Gallegos,AR,-51.6226,-69.2181,37.45,65,0,14.97,clear sky
37,37,Ushuaia,AR,-54.8000,-68.3000,37.06,81,40,25.32,light intensity drizzle
292,292,Egvekinot,RU,66.3167,-179.1667,36.27,95,100,4.29,overcast clouds
68,68,Cherskiy,RU,68.7500,161.3000,34.97,89,100,6.08,light rain
605,605,Pevek,RU,69.7008,170.3133,32.85,90,100,13.71,overcast clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City ID                0
City                   0
Country                0
Lat                    0
Lon                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lon"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lon,Hotel Name
0,Viedma,AR,53.10,light rain,-40.8135,-62.9967,
1,Mar Del Plata,AR,55.13,clear sky,-38.0023,-57.5575,
3,Punta Arenas,CL,37.51,broken clouds,-53.1500,-70.9167,
10,Concordia,AR,49.78,clear sky,-31.3930,-58.0209,
12,Dudinka,RU,56.59,overcast clouds,69.4058,86.1778,
20,Cape Town,ZA,54.27,fog,-33.9258,18.4232,
22,Dunedin,NZ,51.80,overcast clouds,-45.8742,170.5036,
23,Chokurdakh,RU,57.04,overcast clouds,70.6333,147.9167,
25,Port Macquarie,AU,48.88,clear sky,-31.4333,152.9167,
31,Dikson,RU,41.97,overcast clouds,73.5069,80.5464,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row['Lat']
    lon = row['Lon']
    
    params['location'] = f"{lat}, {lon}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url ="https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = req.get(base_url, params = params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try: 
        hotel_df.loc[index, 'Hotel Name'] = hotels['results'][0]['name']
    except(IndexError): 
        print('Hotel not found... Skipping')

Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping
Hotel not found... Skipping

In [9]:
hotel_df.head(40)

,City,Country,Max Temp,Current Description,Lat,Lon,Hotel Name
0,Viedma,AR,53.10,light rain,-40.8135,-62.9967,Hotel Cristal
1,Mar Del Plata,AR,55.13,clear sky,-38.0023,-57.5575,Gran Hotel Mar del Plata
3,Punta Arenas,CL,37.51,broken clouds,-53.1500,-70.9167,Hotel Dreams Del Estrecho
10,Concordia,AR,49.78,clear sky,-31.3930,-58.0209,Palmar Hotel Casino
12,Dudinka,RU,56.59,overcast clouds,69.4058,86.1778,Hotel Viktoria
20,Cape Town,ZA,54.27,fog,-33.9258,18.4232,Southern Sun Waterfront Cape Town
22,Dunedin,NZ,51.80,overcast clouds,-45.8742,170.5036,Scenic Hotel Southern Cross
23,Chokurdakh,RU,57.04,overcast clouds,70.6333,147.9167,
25,Port Macquarie,AU,48.88,clear sky,-31.4333,152.9167,Rydges Port Macquarie
31,Dikson,RU,41.97,overcast clouds,73.5069,80.5464,
33,Sinegorye,RU,45.88,clear sky,62.0788,150.4770,
37,Ushuaia,AR,37.06,light intensity drizzle,-54.8000,-68.3000,Albatros Hotel
40,Castro,BR,40.95,overcast clouds,-24.7911,-50.0119,CHACARA BAILLY
41,Mataura,NZ,48.47,overcast clouds,-46.1927,168.8643,Ellie's Villa
43,Port Alfred,ZA,57.90,scattered clouds,-33.5906,26.8910,The Halyards Hotel
44,Christchurch,NZ,55.00,broken clouds,-43.5333,172.6333,The George
49,Bredasdorp,ZA,43.92,clear sky,-34.5322,20.0403,Bredasdorp Country Manor
51,Berlevag,NO,45.84,overcast clouds,70.8578,29.0864,Kvitbrakka
53,East London,ZA,58.80,clear sky,-33.0153,27.9116,Tu Casa
55,Tuatapere,NZ,48.81,moderate rain,-46.1333,167.6833,Ron and Tony's Bed & Breakfast
59,Muhos,FI,55.18,overcast clouds,64.8080,25.9931,Montta - active camping / campsite Montan
61,Cidreira,BR,50.29,clear sky,-30.1811,-50.2056,Hotel Castelo
68,Cherskiy,RU,34.97,light rain,68.7500,161.3000,Gostinitsa
69,Hermanus,ZA,52.90,clear sky,-34.4187,19.2345,Misty Waves Boutique Hotel
71,Melioratorov,RU,59.38,broken clouds,57.2107,65.6077,Algorithm hotel
75,Beringovskiy,RU,42.66,overcast clouds,63.0500,179.3167,Beringgorski
76,Coihaique,CL,38.01,scattered clouds,-45.5752,-72.0662,Diego De Almagro Coyhaique
77,Busselton,AU,41.09,overcast clouds,-33.6500,115.3333,Observatory Guest House
78,Tiksi,RU,47.97,scattered clouds,71.6872,128.8694,Arktika
80,Upernavik,GL,41.05,broken clouds,72.7868,-56.1549,Gina's Guesthouse - Upernavik
81,New Norfolk,AU,54.90,light rain,-42.7826,147.0587,The Shingles Riverside Cottages
84,Husavik,IS,53.51,clear sky,66.0449,-17.3389,Bjarnabúð
89,Polyarnyy,RU,48.67,overcast clouds,69.1989,33.4478,Hotel Tatyana
92,Hobart,AU,55.26,light rain,-42.8794,147.3294,Mantra on Collins Hobart
93,Barrow,US,51.82,light rain,71.2906,-156.7887,King Eider Inn
95,Tasiilaq,GL,50.16,few clouds,65.6145,-37.6368,The Red House
98,Broken Hill,AU,55.15,clear sky,-31.9500,141.4333,Royal Exchange Hotel
100,Angouleme,FR,59.32,clear sky,45.6500,0.1500,Mercure Angoulême - Hôtel de France
105,Nanortalik,GL,45.10,overcast clouds,60.1432,-45.2371,Hotel Kap Farvel
106,Casma,CL,47.48,scattered clouds,-41.0082,-73.1244,Hospedaje Casma

In [10]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df['Hotel Name'].replace('', np.nan, inplace = True)
hotel_df.dropna(subset = ['Hotel Name'], inplace = True)
hotel_df.head(40)

,City,Country,Max Temp,Current Description,Lat,Lon,Hotel Name
0,Viedma,AR,53.10,light rain,-40.8135,-62.9967,Hotel Cristal
1,Mar Del Plata,AR,55.13,clear sky,-38.0023,-57.5575,Gran Hotel Mar del Plata
3,Punta Arenas,CL,37.51,broken clouds,-53.1500,-70.9167,Hotel Dreams Del Estrecho
10,Concordia,AR,49.78,clear sky,-31.3930,-58.0209,Palmar Hotel Casino
12,Dudinka,RU,56.59,overcast clouds,69.4058,86.1778,Hotel Viktoria
20,Cape Town,ZA,54.27,fog,-33.9258,18.4232,Southern Sun Waterfront Cape Town
22,Dunedin,NZ,51.80,overcast clouds,-45.8742,170.5036,Scenic Hotel Southern Cross
25,Port Macquarie,AU,48.88,clear sky,-31.4333,152.9167,Rydges Port Macquarie
37,Ushuaia,AR,37.06,light intensity drizzle,-54.8000,-68.3000,Albatros Hotel
40,Castro,BR,40.95,overcast clouds,-24.7911,-50.0119,CHACARA BAILLY
41,Mataura,NZ,48.47,overcast clouds,-46.1927,168.8643,Ellie's Villa
43,Port Alfred,ZA,57.90,scattered clouds,-33.5906,26.8910,The Halyards Hotel
44,Christchurch,NZ,55.00,broken clouds,-43.5333,172.6333,The George
49,Bredasdorp,ZA,43.92,clear sky,-34.5322,20.0403,Bredasdorp Country Manor
51,Berlevag,NO,45.84,overcast clouds,70.8578,29.0864,Kvitbrakka
53,East London,ZA,58.80,clear sky,-33.0153,27.9116,Tu Casa
55,Tuatapere,NZ,48.81,moderate rain,-46.1333,167.6833,Ron and Tony's Bed & Breakfast
59,Muhos,FI,55.18,overcast clouds,64.8080,25.9931,Montta - active camping / campsite Montan
61,Cidreira,BR,50.29,clear sky,-30.1811,-50.2056,Hotel Castelo
68,Cherskiy,RU,34.97,light rain,68.7500,161.3000,Gostinitsa
69,Hermanus,ZA,52.90,clear sky,-34.4187,19.2345,Misty Waves Boutique Hotel
71,Melioratorov,RU,59.38,broken clouds,57.2107,65.6077,Algorithm hotel
75,Beringovskiy,RU,42.66,overcast clouds,63.0500,179.3167,Beringgorski
76,Coihaique,CL,38.01,scattered clouds,-45.5752,-72.0662,Diego De Almagro Coyhaique
77,Busselton,AU,41.09,overcast clouds,-33.6500,115.3333,Observatory Guest House
78,Tiksi,RU,47.97,scattered clouds,71.6872,128.8694,Arktika
80,Upernavik,GL,41.05,broken clouds,72.7868,-56.1549,Gina's Guesthouse - Upernavik
81,New Norfolk,AU,54.90,light rain,-42.7826,147.0587,The Shingles Riverside Cottages
84,Husavik,IS,53.51,clear sky,66.0449,-17.3389,Bjarnabúð
89,Polyarnyy,RU,48.67,overcast clouds,69.1989,33.4478,Hotel Tatyana
92,Hobart,AU,55.26,light rain,-42.8794,147.3294,Mantra on Collins Hobart
93,Barrow,US,51.82,light rain,71.2906,-156.7887,King Eider Inn
95,Tasiilaq,GL,50.16,few clouds,65.6145,-37.6368,The Red House
98,Broken Hill,AU,55.15,clear sky,-31.9500,141.4333,Royal Exchange Hotel
100,Angouleme,FR,59.32,clear sky,45.6500,0.1500,Mercure Angoulême - Hôtel de France
105,Nanortalik,GL,45.10,overcast clouds,60.1432,-45.2371,Hotel Kap Farvel
106,Casma,CL,47.48,scattered clouds,-41.0082,-73.1244,Hospedaje Casma
109,Nome,US,51.17,light rain,64.5011,-165.4064,Dredge 7 Inn
111,Krasnovishersk,RU,50.88,scattered clouds,60.4078,57.0820,Vishera
113,Codrington,AU,49.95,light rain,-38.2667,141.9667,Codrington Gardens Bed And Breakfast

In [11]:
# 8a. Create the output File (CSV)

output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [31]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt> Current Description </dt><dd> {Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lon"]]

In [32]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content = hotel_info)

# 11b. Display the figure
fig = gmaps.figure(center = (30.0, 31.0), zoom_level = 1.5)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))